<?php
// Module C/admin_generate_report.php
session_start();
require_once '../includes/db_connection.php';

if (!isset($_SESSION['admin_id'])) {
    die("Access Denied");
}

$report_date = date("d M Y, h:i A");

$res_rev = $conn->query("SELECT SUM(total_price) as rev FROM bookings WHERE booking_status = 'confirmed'");
$revenue = $res_rev->fetch_assoc()['rev'] ?? 0;

$res_bk = $conn->query("SELECT COUNT(*) as total FROM bookings");
$total_bookings = $res_bk->fetch_assoc()['total'];

$today = date('Y-m-d');
$res_up = $conn->query("SELECT COUNT(*) as up FROM bookings WHERE booking_status = 'confirmed' AND check_in_date >= '$today'");
$upcoming = $res_up->fetch_assoc()['up'];

$sql_list = "SELECT b.*, r.room_name, u.full_name, u.email 
             FROM bookings b 
             JOIN rooms r ON b.room_id = r.room_id 
             LEFT JOIN users u ON b.user_id = u.user_id 
             WHERE b.booking_status = 'confirmed'
             ORDER BY b.check_in_date DESC LIMIT 50";
$list = $conn->query($sql_list);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Generating Report...</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <style>
        body { font-family: 'Helvetica', Arial, sans-serif; background: #555; padding: 30px; }
        
        #report-content {
            background: white;
            width: 210mm;
            min-height: 297mm;
            margin: 0 auto;
            padding: 20mm;
            box-shadow: 0 0 10px rgba(0,0,0,0.5);
        }

        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #d35400; text-transform: uppercase; }
        .sub-header { color: #666; font-size: 14px; margin-top: 5px; }
        
        .summary-box { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .stat-item { width: 30%; background: #f8f9fa; padding: 15px; border: 1px solid #ddd; text-align: center; }
        .stat-val { font-size: 20px; font-weight: bold; color: #333; margin-top: 5px; display: block;}
        .stat-label { font-size: 12px; color: #777; text-transform: uppercase; }

        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #333; color: white; }
        tr:nth-child(even) { background-color: #f9f9f9; }

        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        
        .loading { color: white; text-align: center; font-size: 20px; margin-bottom: 20px; }
    </style>
</head>
<body>

    <div class="loading" id="loadingMsg">Creating PDF... Please wait.</div>

    <div id="report-content">
        <div class="header">
            <div class="logo">Teh Tarik No Tarik Homestay</div>
            <div class="sub-header">Business Performance Report</div>
            <div class="sub-header">Generated on: <?php echo $report_date; ?></div>
            <div class="sub-header">Generated by: <?php echo htmlspecialchars($_SESSION['username']); ?></div>
        </div>

        <div class="summary-box">
            <div class="stat-item">
                <span class="stat-label">Total Revenue</span>
                <span class="stat-val" style="color:#27ae60;">RM <?php echo number_format($revenue, 2); ?></span>
            </div>
            <div class="stat-item">
                <span class="stat-label">Total Bookings</span>
                <span class="stat-val"><?php echo $total_bookings; ?></span>
            </div>
            <div class="stat-item">
                <span class="stat-label">Upcoming Stays</span>
                <span class="stat-val" style="color:#e67e22;"><?php echo $upcoming; ?></span>
            </div>
        </div>

        <h4 style="border-bottom: 2px solid #eee; padding-bottom: 10px;">Recent Confirmed Bookings (Last 50)</h4>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Customer</th>
                    <th>Room</th>
                    <th>Check-In / Out</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($list->num_rows > 0): ?>
                    <?php while($row = $list->fetch_assoc()): ?>
                        <tr>
                            <td>#<?php echo $row['booking_id']; ?></td>
                            <td>
                                <b><?php echo htmlspecialchars($row['full_name']); ?></b><br>
                                <span style="color:#666;"><?php echo $row['email']; ?></span>
                            </td>
                            <td><?php echo $row['room_name']; ?></td>
                            <td>
                                <?php echo $row['check_in_date']; ?><br>
                                to <?php echo $row['check_out_date']; ?>
                            </td>
                            <td style="font-weight:bold;">RM <?php echo number_format($row['total_price'], 2); ?></td>
                        </tr>
                    <?php endwhile; ?>
                <?php else: ?>
                    <tr><td colspan="5" style="text-align:center;">No confirmed records found.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>

        <div class="footer">
            Confidential Report • For Internal Use Only • Teh Tarik No Tarik Management System
        </div>
    </div>

    <script>
        window.onload = function() {
            const element = document.getElementById('report-content');
            const opt = {
                margin:       10,
                filename:     'Homestay_Report_<?php echo date("Ymd"); ?>.pdf',
                image:        { type: 'jpeg', quality: 0.98 },
                html2canvas:  { scale: 2 },
                jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
            };

            html2pdf().set(opt).from(element).save().then(function(){
                document.getElementById('loadingMsg').innerText = "Report Downloaded! You can close this tab.";
            });
        };
    </script>

</body>
</html>